name       : perl-file-path
version    : '2.18'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/J/JK/JKEENAN/File-Path-2.18.tar.gz : 980f0a17edb353df46e9cd7b357f9f5929cde0f80c45fd7a06cf7e0e8bd6addd
homepage   : https://metacpan.org/pod/File::Path
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Path - Create or remove directory trees
description: |
    This module provides a convenient way to create directories of arbitrary depth and to delete an entire directory subtree from the filesystem.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
